## Copyright (c) 2026 John Pursey
##
## Use of this source code is governed by an MIT-style License that can be found
## in the LICENSE file or at https://opensource.org/licenses/MIT.

# Writes the header at OUTPUT with the git commit of SOURCE_DIR, and whether
# its tracked files have changes, for the profile snapshot. Run on every build
# with GIT set to the git executable. The header is only rewritten when it
# changes, so a build with no change recompiles nothing.

execute_process(
  COMMAND "${GIT}" rev-parse --short HEAD
  WORKING_DIRECTORY "${SOURCE_DIR}"
  OUTPUT_VARIABLE commit
  OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE commit_result)
if(NOT commit_result EQUAL 0)
  set(commit "unknown")
endif()

execute_process(
  COMMAND "${GIT}" diff --quiet HEAD
  WORKING_DIRECTORY "${SOURCE_DIR}"
  RESULT_VARIABLE diff_result)
if(diff_result EQUAL 0)
  set(modified "false")
else()
  set(modified "true")
endif()

set(content "// Generated by build_info.cmake on every build. Don't edit.

#pragma once

namespace jpr {

inline constexpr char kBuildCommit[] = \"${commit}\";
inline constexpr bool kBuildModified = ${modified};

}  // namespace jpr
")

if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" old_content)
endif()
if(NOT content STREQUAL old_content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
